export const SHOWLISTRECIPE = "SHOWLISTRECIPE";
export const SHOWRECIPEDETAIL = "SHOWRECIPEDETAIL";
export const INPUTTOCART = "INPUTTOCART";
export const SHOWCART = "SHOWCART";
export const ONPAYMENT = "ONPAYMENT";
export const PAYMENT = "PAYMENT";
export const VOTE = "VOTE";
export const SUBMITCOMMENT = "SUBMITCOMMENT";
