export const SHOWINFOR = "SHOWINFOR";
export const CHANGEPASSWORD = "CHANGEPASSWORD";
export const LISTRECIPE = "LISTRECIPE";
export const CREATERECIPE = "CREATERECIPE";
export const RECHARGEMONEY = "RECHARGEMONEY";
export const WITHDRAWMONEY = "WITHDRAWMONEY";
export const TRANSACTIONHISTORY = "TRANSACTIONHISTORY";
export const USERRECIPEDETAIL = "USERRECIPEDETAIL";
